name: Merge test into main on Release

on:
  release:
    types: [published]  # Läuft, wenn ein neues Release veröffentlicht wird

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Merge test into main
        run: |
          git checkout main
          git pull origin main
          git merge --no-ff test -m "Automated merge from test to main"
          git push origin main
